# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 357d1fc3e3a71d170f081d5b4ba8da47be2deb18b07a6c715dae708d0a0ab52a79f99ba1bf5e84dc1757098a32bb0512bac10267d1a2c9e28a1c7ccb9ed91d55

test:
  secret_key_base: aaefd3aed20e89205b9cfb6374b2ee7577646a618daab8d2a7dd81bece76719ead3973249d84eb6f24a5620319bee8885bc5186a0ab4e869e768fe087150c411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
